version: '2'
services:
  consul:
    image: consul:1.6
    ports:
      - '8300:8300'
      - '8500:8500'
      - '8600:8600'
    volumes:
      - ./data/consul:/data
      - ./config:/config
    command: agent -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -ui
  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - RABBITMQ_USERNAME=wazo
    - RABBITMQ_PASSWORD=wazo
    volumes:
    - ./data/rabbitmq:/bitnami/rabbitmq